package com.example.generated;

import com.example.ExampleBootstrap;
import com.xiaomi.youpin.infra.rpc.Result;
import lombok.extern.slf4j.Slf4j;
import org.junit.After;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.UUID;

// TODO: 按本项目实际情况，导入登录上下文 / 请求头 / 序列化等工具类
// 例如：
// import <package>.common.LoginUserThreadLocal;
// import <package>.common.po.LoginUserPo;
// import <package>.dto.common.XxxModifyHeader;
// import <package>.util.GsonUtil;

/**
 * API 测试基类 — 提供公共 setup/teardown 和断言工具方法
 * Generated by: @digital-user/api-test-framework
 *
 * 注意：本基类为通用骨架。setupLoginUser / createHeader / logResult 中标注 TODO 的部分
 *      需按本项目的登录上下文、请求头、序列化工具补全后才能编译运行。
 */
@Slf4j
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ExampleBootstrap.class})
@ActiveProfiles("dev")
public abstract class ApiTestBase {

    @After
    public void tearDown() {
        // TODO: 清理登录上下文，例如 LoginUserThreadLocal.removeLoginUser();
    }

    protected void setupLoginUser(String account) {
        // TODO: 设置登录上下文，例如：
        // LoginUserPo loginUser = new LoginUserPo();
        // loginUser.setAccount(account);
        // LoginUserThreadLocal.setLoginUser(loginUser);
    }

    // TODO: 返回本项目的请求头类型，替换 Object 为实际 Header 类型
    protected Object createHeader() {
        // 示例：
        // XxxModifyHeader header = new XxxModifyHeader();
        // header.setRequestId(UUID.randomUUID().toString());
        // header.setTimestamp(System.currentTimeMillis());
        // return header;
        return null;
    }

    protected <T> void assertSuccess(Result<T> result) {
        org.junit.Assert.assertNotNull("result should not be null", result);
        org.junit.Assert.assertEquals("result code should be 0", 0, (int) result.getCode());
    }

    protected void logResult(String caseId, Object result) {
        // TODO: 用本项目的序列化工具打印，例如 GsonUtil.toJSONString(result)
        log.info("[{}] result: {}", caseId, result);
    }
}
